### ISSUE TITLE
Nexus 5: power on has to be pressed repeatedly to wake up the phone

### ISSUE THREAD

**Issue by wagafo** [ubports/ubports-touch#124] opened 2017-06-22 07:23 UTC
To wake up the Nexus 5 from suspend, the power button has to be pressed 3 times.

**Comment by Flohack74** [comment] 2017-06-22 13:52
Duplicate of https://github.com/ubports/ubports-touch/issues/65

**Closed by Flohack74** 2017-06-22 13:52 UTC
