### ISSUE TITLE
 Screen toggles while off & charging 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#34] opened 2017-05-27 22:41 UTC
The FP2 screen toggles between the battery indicator and the FP2 Logo with a pause in between, when the phone is turned off & charging.

reported by https://launchpad.net/~snapdeb.

This seems to be a kernel bug that the Nexus 5X shared when it was in development. I'm triaging it as a wishlist since it doesn't affect day-to-day use of the device.

added by https://launchpad.net/~universalsuperbox

Mine reboots on loop when charging, it's impossible to turn it off.

reply from https://launchpad.net/~mgc.lude

If you hold the power button long enough, the device will boot normally. Might take around 20 seconds.

reply from https://launchpad.net/~universalsuperbox

Actually seems to be a little more serious than this as the device appears to heat up...even though not on. Is this a safety issue potentially?
reply from https://launchpad.net/~andybleaden

**Comment by peat-psuwit** [comment] 2017-06-04 16:52
Ok, it happens that the "charger" binary (responsible for displaying battery animation) clash with Ubuntu's graphical component. By disabling "lightdm" service, the system doesn't reboot.

So, I implement proper root selection in initrd so that if the system boot because of charger mode, it'll use the Android rootfs. This way, Ubuntu components won't start at all and charging works properly.

Please try this boot.img if it fixes the problem: [boot.img.gz](https://github.com/ubports/ubports-touch/files/1050536/boot.img.gz)

@bastos77, please also check if this fix #50 too.

**Comment by NeoTheThird** [comment] 2017-06-06 19:30
Isn't this #50? I think this is a duplicate.

**Comment by peat-psuwit** [comment] 2017-06-07 19:04
I already mark #50 as a duplicate of this issue.

**Comment by peat-psuwit** [comment] 2017-06-07 19:25
Fixed in ubports/initramfs-tools-ubuntu-touch@947dd406d1c820a217105ac6a57b5d640e8f0d54 along with ubports/android_build@7baaf5028b0076d53d39c00d5f8e3d6ab0309fad

**Closed by peat-psuwit** 2017-06-07 19:25 UTC
Labels: bug, device: FP2
