### ISSUE TITLE
Camera does not work

### ISSUE THREAD

**Issue by siucdude** [ubports/ubports-touch#110] opened 2017-06-14 17:08 UTC
Bacon 15.04/devel r27

See attached screenshot but after recent update, the camera app does not work, and you cant change permissions
![screenshot20170614_120413277](https://user-images.githubusercontent.com/6015094/27145116-16fdc466-50fa-11e7-99f8-0cb8adff06ba.png)
 as its all grayed out.

**Comment by NeoTheThird** [comment] 2017-06-14 17:45
Duplicate of #14.

**Closed by NeoTheThird** 2017-06-14 17:45 UTC
