### ISSUE TITLE
no audio

### ISSUE THREAD

**Issue by ProsOne** [ubports/ubports-touch#205] opened 2017-08-07 08:59 UTC
There is no audio from some apps like music, uradio, notification settings, Cloud music etc..The only sound I hear comes from the keyboard, or from YouTube app
I'm on nexus4, last devel update

**Comment by garro95** [comment] 2017-08-07 09:06
This is #58. Please put +1 on  that and close this

**Comment by Flohack74** [comment] 2017-08-07 09:16
Duplicate of #58

**Closed by Flohack74** 2017-08-07 09:16 UTC
