### ISSUE TITLE
Not obvious and friendly management of the various sound volume

### ISSUE THREAD

**Issue by TronFourtyTwo** [ubports/ubports-touch#204] opened 2017-08-06 20:26 UTC
There are different volume for different contexts, for example the alarm volume, the phone call one... From the Sound indicator is possible to modify only the current used one, but this is very unpratical.

**Comment by Flohack74** [comment] 2017-08-06 21:22
Duplicate of #81

**Closed by Flohack74** 2017-08-06 21:22 UTC
