### ISSUE TITLE
 Long boot time 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#53] opened 2017-05-28 00:23 UTC
It seem to use little over 3 minutes to boot

It uses 3.19 minutes to reach ubuntu's bootscreen. and another 10seconds to fully boot. The issue here is before unity-system-compositor-spinner starts.

**Comment by prpldvl67** [comment] 2017-05-30 13:45
Hi Guys I have installed it on AQuaris E5 hd and works wonders can it be installed on M 10 FHD or still problems with booting?

**Comment by NeoTheThird** [comment] 2017-05-30 13:53
@prpldvl67 As you can read in the issue report, the device works, but takes very long to boot. Here's how to install: https://devices.ubports.com/#/frieza

**Comment by prpldvl67** [comment] 2017-06-02 13:47
BTW I have flashed device it boots and start up fantastic no delay ...

**Comment by WLBI** [comment] 2017-06-07 18:14
Great, I just realized, the M 10 FHD is booting now much more fast. It takes 22 seconds from power on to login screen.
I guess, this bug is no bug anymore ;-)

**Comment by thedimmu** [comment] 2017-06-07 20:36
On my M10 FHD booting still needs some Minutes before the ubports screen appears. From here everything goes on normaly.

**Comment by WLBI** [comment] 2017-06-08 06:58
@thedimmu 
oh I am sorry.. lol
I just made test installation of the original Ubuntu image to make some other tests and I forgot that I am using this. ;-)

**Comment by prpldvl67** [comment] 2017-06-08 18:59
Hi, still takes three minutes but since moving to ubports both tablet and phone run much more smoother the phone in particular... Looking forward to faster booting

**Comment by osmoma** [comment] 2017-06-29 19:36
Yes, the boot time is very long time (several minutes) on Ubuntu Aquaris M10 FHD.
I run the latest UBPort 15.04 (r1)

**Comment by mariogrip** [comment] 2017-09-24 03:39
Found the issue, kernel/initrd bug fixrtc was waiting for nonexisting root) Fix pushed to devel. Please give it a test

**Closed by mariogrip** 2017-09-24 03:39 UTC
Labels: bug, device: frieza

**Comment by prpldvl67** [comment] 2017-09-24 06:02
Hi Mario, OTA 2 downloaded but still takes long time is there a patch to download? BTW OTA2 is superb well done! thanks

**Comment by andipeer** [comment] 2017-09-24 17:12
I can confirm that this is not an issue anymore on devel :)

**Comment by prpldvl67** [comment] 2017-09-24 17:51
Hi yes does indeed on devel; will it also be available on RC?

**Comment by Flohack74** [comment] 2017-09-25 16:13
Soon when we push devel to rc, we try to do this more often now ;)

**Comment by PaskoMoto** [comment] 2017-11-04 14:17
Hi.
Any plans to push this into RC in the near future?
Also: Can I flash the devel branch in the same way as I flashed the stable version?
Thank you for your work.
