### ISSUE TITLE
Hammerhead - Devel : GPS getting stuck

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-touch#186] opened 2017-07-29 23:56 UTC
I've noticed with the recent devels the gps apps got stuck and time to time Unav see it's permission revoked during a guidance. 
I'm back to rc for further tests, to unsure it's from Devel.

**Comment by Flohack74** [comment] 2017-08-04 21:21
Ok can you tell us then if you can confirm the problem is in current devel? No one touched GPS I think... @mariogrip ?

**Comment by ernesst** [comment] 2017-08-08 01:58
My last try on the devel was ok, i switched back to rc for my holidays. I'll try back in september.

**Comment by NeoTheThird** [comment] 2017-08-10 09:53
Ok, thanks. Let's close this for now.

**Closed by NeoTheThird** 2017-08-10 09:53 UTC
Labels: question
