### ISSUE TITLE
Start is very long

### ISSUE THREAD

**Issue by laurentGarry** [ubports/ubports-touch#99] opened 2017-06-11 18:23 UTC
The startup lasts more than 3 minutes

**Comment by Flohack74** [comment] 2017-06-11 18:46
Please be more specific, which device & which channel you are on?

**Comment by laurentGarry** [comment] 2017-06-12 05:52
Is it "Ubuntu 15.4 (R11)"
I had a problem with the UT start Ubports before the M10 tablet started up very fast

**Comment by Flohack74** [comment] 2017-06-12 07:39
@NeoTheThird what do we  know about start times of the tablets right now? Whats your experience?

**Comment by samtygier** [comment] 2017-06-12 08:07
Duplicate of #53

**Comment by NeoTheThird** [comment] 2017-06-12 09:40
This has already been reported on #53.

**Closed by NeoTheThird** 2017-06-12 09:40 UTC
Labels: question
