### ISSUE TITLE
FP2 (new batch) blue screen

### ISSUE THREAD

**Issue by wouter-glasswall** [ubports/ubports-touch#253] opened 2017-09-19 14:36 UTC
- Device: FP2 (New Batch 9-2017)
- Channel:
- Build: r1 /device image part 20170610-1369

## Steps to reproduce

1. new FP2 (new camera module & different screen *FP2 TM-C2*)
2. CPT -> reboot to recovery -> blue screen 
3. CPT -> install ubuntu  -> download + push 
4. Ubuntu is installed on your device -> reboot -> blue screen

## Expected behavoir
Install Ubuntu touch
...

## Actual behavior
CPT -> reboot to recovery -> screen blue & recovery adb works

adb devices 
List of devices attached
fc3f681	recovery

After the phone reboots, the screen remains blue (no adb) and results in a bootloop

## Logfiles and additional information
Placing the new screen *FP2 TM-C2* my "old" fairphone (Ubuntu r1) will result in a blue screen and bootloop.

After placing a "old" screen *FP2 TM-C1* on my phone (new batch) its boots normal. After I've completed the setup wizard and enabled adb, I've replaced the old *FP2 TM-C1* to the new screen *FP2 TM-C2*. The phone (new batch+ new screen) will boot with a bluescreen and with a active adb connection.

 [UTdmesg.txt](https://github.com/ubports/ubports-touch/files/1314555/UTdmesg.txt)

[UTlogcat.txt](https://github.com/ubports/ubports-touch/files/1314561/UTlogcat.txt)
![photo_2017-09-19_08-25-15](https://user-images.githubusercontent.com/8579281/30596646-0782eab4-9d55-11e7-9e44-f2081bd68c1b.jpg)

**Comment by jaapjansma** [comment] 2017-09-20 15:03
I am more tha happy to help to fix this bug. But I have no clue what to do.

**Comment by NeoTheThird** [comment] 2017-09-20 19:08
The problem is that our port is on android 5.x, but the new components were introduced after the Fairphone OS was re-based to Android 6.x, so the drivers are different...

Maybe @mariogrip can provide insight on what needs to be done to fix this. Do we need a new port?

@jaapjansma Thank you, all help is appreciated. Do you have experience in android porting and low-level development?

**Comment by jaapjansma** [comment] 2017-09-21 10:30
@NeoTheThird I don't have any experience in android porting and low level development.

**Comment by YtvwlD** [comment] 2017-09-22 17:33
Hi! I've ran into this same issue today with my new refurbished FP2 ("New Life Edition").
I'm happy to help if there's anything I can do.

**Comment by ttxtea** [comment] 2017-09-28 16:27
Have the same problem (unfortunately read this only after trying :-) ). Is it a possibility to downgrade Android 6.1 to 5.x and then install ubports?

**Comment by Flohack74** [comment] 2017-09-28 19:22
We are working on a fix already, see here: https://github.com/ubports/android_kernel_fairphone_fp2/pull/3

**Comment by tforgione** [comment] 2017-10-03 17:19
Just bought a new fairphone 2, and tried to install ubports on it, and i god the blue screen of death :stuck_out_tongue: 

I see that ubports/android_kernel_fairphone_fp2#3 has been merge. Does this mean [ubports/ubports-installer](https://github.com/ubports/ubports-installer/) will have a new release soon ?

Thanks

**Comment by mariogrip** [comment] 2017-10-03 17:29
@tforgione The UBports installer already has support for the new screen. but you need to install the devel channel since there is where the changes are pushed to. rc and stable will get the fix later

**Comment by tforgione** [comment] 2017-10-03 17:34
Oh nice, this is what I am currently doing. Thank you very much for the quick answer !

**Comment by Flohack74** [comment] 2017-10-04 17:02
So we got confirmation that it works. Thanks and closing :)

**Closed by Flohack74** 2017-10-04 17:02 UTC
Labels: bug, device: FP2

**Comment by jaapjansma** [comment] 2017-10-10 16:32
@Flohack74 I have just installed the devel channel on my Fairphone2 and I still have a blue screen.

**Comment by ttxtea** [comment] 2017-10-10 16:47
I tried it as well with the latest fairphone2 (android 6.1) and it
worked perfectly!

**Comment by jaapjansma** [comment] 2017-10-10 17:42
@ttxtea thanks for your comment. It seems to work it looked like it did not pickup the devel channel previously.

**Comment by Anne017** [comment] 2017-10-19 20:00
Strange, [I can't do that](https://github.com/ubports/ubports-installer/issues/36)...
@ttxtea @jaapjansma @tforgione How did you do? What am I missing?

**Comment by ttxtea** [comment] 2017-10-20 08:30
I had to do the "reboot" or "boot to secure/developper mode" several
times. Always waiting in between. I think I also "Power+volume down"
and "Power+volume up" in alternation. At some point the installer
recognised it and proceeded. It was a bit mysterious ... but then it
worked perfectly.

**Comment by Anne017** [comment] 2017-10-20 20:13
I tried "Power+volume down", wait more than a minute, "Power+volume up", wait more than a minute, "Power+volume down", wait more than a minute, "Power+volume up", wait more than a minute, etc.
Also "Power+volume down+up", wait more than a minute.
Nothing...
But thanks for your help.

**Comment by ttxtea** [comment] 2017-10-21 16:24
And you are sure you are using this version 0.1.7-beta?

https://github.com/ubports/ubports-installer/releases

**Comment by Anne017** [comment] 2017-10-22 20:01
Yes, I used the "ubports-installer-0.1.7-beta-x86_64.AppImage" file.

**Comment by ttxtea** [comment] 2017-10-23 08:10
Hmm - 

I 've used a lubuntu 17.04 to do the installation from (it was an X1
carbon machine). Its really odd why it does not work in your case. 

What you are saing is that you don't get the blue screens but it
stopps at the black "fairphone powerd by android" screen - right?
Does it also mean that with the pld ubports intaller 0.1.6. you are
getting further in your unstallation?


- you can try different usb calbes and usb ports.
- it could be that some thing is wrong with the mobil phone afterall.

wish I could be of more help

ps: once it works ubtouch is really great experience.
