### ISSUE TITLE
Cooler - Wifi Not Connect after restart or Shutdown.

### ISSUE THREAD

**Issue by FabioCAMachado** [ubports/ubports-touch#76] opened 2017-06-03 05:47 UTC
Hi, anybody know how can I fix the problem with wifi on b M10? Wen I turn the tablet off and restart the wifi not connect. In setting wifi the password is OK but not connect. I need put the password again to connect.
Thanks for any help.
[UTlogcat.log.zip](https://github.com/ubports/ubports-touch/files/1049411/UTlogcat.log.zip)

**Comment by WLBI** [comment] 2017-06-03 11:58
This even happens, when turn off and on Wi-Fi connection, without reboot. After that you need to re-enter the Wi-Fi password again.

**Comment by WLBI** [comment] 2017-06-03 14:24
@Flohack74 
Actually it's not a question, it should be a bug report.

**Comment by Flohack74** [comment] 2017-06-03 18:45
I disagree with @mariogrip since we have a bunch of people who reported its ok, so for me the question is, what we can do to find out where this comes from? For me its not necessarily a bug tbh...

**Comment by NeoTheThird** [comment] 2017-06-03 19:01
The title says M10 HD, that would be cooler.

**Comment by FabioCAMachado** [comment] 2017-06-03 22:20
The title are fixed. Sorry.

**Comment by Flohack74** [comment] 2017-06-03 22:52
BQ M10 HD is ok for the title, its just our labels that werent right ;)

**Comment by WLBI** [comment] 2017-06-04 05:58
ok, so I am in the wrong thread. 
I have this problem on the M10 FHD/Frieza not HD/Cooler. Don't tell me to open a new thread... ;)

**Comment by NeoTheThird** [comment] 2017-06-04 08:03
@WLBI No, you don't need to add a second bug, since these are most certainly connected. I was just confused because the labels were wrong in the beginning.

@FabioCAMachado are you sure you have the M10 HD? It seems to work fine on my device. Please open Settings -> About and see what it says there. I may have to investigate this...

**Comment by FabioCAMachado** [comment] 2017-06-04 08:15
Yes. I sure about that. I just checked this now.  The device is bq Aquaris M10 HD Ubuntu Edition.

**Comment by WLBI** [comment] 2017-06-04 08:25
I have the FHD and in my "About" it shows
Serial: 0123456789ABCDEF
Looks weired...

**Comment by FabioCAMachado** [comment] 2017-06-04 08:31
Thats really strange  because my one have the some serial but M10 HF.
I refresh  my tablet with  the bq  tools.

**Comment by NeoTheThird** [comment] 2017-06-04 08:40
@WLBI On my device (cooler), the serial number is displayed correctly. Please open a seperate issue since this is probably unrelated.

**Comment by WLBI** [comment] 2017-06-04 10:17
Well, I also had a German conversation with Marius Q. one week ago, because first I was not able to install UBports on my tab, because the cache was full.

```
$ adb shell "df -h"
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   981.1M     36.0K    981.0M   0% /dev
tmpfs                   981.1M     12.0K    981.0M   0% /tmp
/dev/block/platform/mtk-msdc.0/by-name/userdata
                          9.3G     76.2M      9.2G   1% /data
/dev/block/platform/mtk-msdc.0/by-name/system
                          3.8G      3.7G     52.4M  99% /cache
```

Then Marius Gripsgard told me a solution how to do it.

`adb shell "make_ext4fs /dev/block/platform/mtk-msdc.0/by-name/system"
adb reboot bootloader
`
After that I was able to install UBports.

Marius Quabeck told me, that the hardware is broken:
Somehow translated from German to Englisch:
Your nvram is broken and because of that it can't empty by udf.
You still have problems on Ubuntu, because your network manager isn't working without nvram.
For example it can't remember wifi. 
Send it to bq, you can't make bugreports with that device.

_Here the German text which he sended me on Telegram_: http://paste.ubuntu.com/24770391/

I asked Marius Gripsgard about that too and he told me, that he don't think that the hardware is broken.

But that's actually what Marius Quabeck said, that the Network manager with wifi will not work.
So what are your thoughts about that?
But actually I don't know what nvram means and what he means by "can't empty by oidf"

**Comment by Flohack74** [comment] 2017-06-04 18:28
Ok now it makes sense, I remember that. Yes its possible that overflashing the nvram has some consequences for the OS later on. So Marius Q was right: Send it to BQ for IMEI/nvram repair. Seems the only option for you, since no one else has got this problem (except the other guys, so probably he´s got an empty nvram too)

**Comment by Flohack74** [comment] 2017-06-04 18:30
We leave this open for 2 or 3 days, and then it will be closed as this is not an UBports bug...

**Comment by WLBI** [comment] 2017-06-04 20:46
hmm,
I just installed Ubuntu Touch Version 7 from Canonical with the SP-Flash-Tool.
There it's the same problem. Everytime I reboot, I have to enter the Wi-Fi password, it's not saved.

**Comment by NeoTheThird** [comment] 2017-06-09 12:05
I still can't reproduce this on cooler.

**Comment by SanderKSmit** [comment] 2017-06-14 17:15
Same problem on my m10fhd 
At each reboot wifi won't connect and I have to enter wpa key

**Comment by Flohack74** [comment] 2017-06-25 18:36
I close this now, probably in all cases that observe this behaviour the reason is that the NVRAm has been accidently deleted, and only a BQ service employee can fix that again.

BR

**Closed by Flohack74** 2017-06-25 18:36 UTC
Labels: device: cooler, device: frieza, question

**Comment by WLBI** [comment] 2017-07-07 17:24
Just want to inform you, that I get in touch with BQ and they changed the device. I told them, the problems and that probably the nvram is damaged.
I sended them my old M10 and they sended me a new one.
Well, but unfortunately they don't have stock of the BQ M10 Ubuntu Edition anymore, so they asked me if it is ok to replace with an Android version.
I told them, never mind, I will flash it with UBports, so it's ok. ;-)

**Comment by simoxxx** [comment] 2019-02-11 18:31
https://github.com/ubports/ubuntu-touch/issues/1040#issuecomment-462430574
